apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QgdKnSK5zO8iJafrrrAPFZE/0c4=,iv:H2+6x7G//wfBC2bA9iqSSLbH87AmouiQ8NGoDJDw0nA=,tag:MXtyUMMgspZEeUb2TTEDRA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J2EzpB0akPjQw4qfrhIagQK72XH8SzPiR6weq5ioQE2ucYbQmNS5FQ==,iv:bNMD1AjQ7vFsYaPAes/hccYflmzZmAinJakzSriOBIw=,tag:vz/FfS3OpXUGmOdg9INZKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eXRUaHdSdTAzakY5aTRK
            RWxXQUUyclpEZzcxTENwNlZ5SG1YZ2MwOWlzCloraVAydi9qblh4ZnJnRGNBbVln
            eFNkSTg2aGRtM3ppVzZkN1BvMW5kVmcKLS0tIGhoN3dWRzlCR0JsdUJkQTlVbU5p
            RDNhRU5TWms5c1ZXVHpoZ1B3V0ZXV0EKAbTPCRbZxmbX1Y0NUE0Covb4MsEQrpyv
            fvJXv6PTRK+xLya8mYVgudR93bCDwzn7GDrrvKjdBLSApZbSOp3EgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T09:06:05Z"
    mac: ENC[AES256_GCM,data:FS4rTJvvY9ZiQZnYHWcMDIAvEECDGhbWNq/Cdfd62RYBXFSryLEgmvKUBqJk7jKjjbe7W939gSszgjvCluAENY6RoYtQKmdGSeBaziWcB0ttI6R5l3Y+Dq18hOiIp4IapoQMnu0X0S3/cucbH55u0UkkXJdjCCnSHWVsnoWwZxk=,iv:wPkrqmQKXHuVYFGH8dRcyevhEvBo7OQIA6ORjiAIYZo=,tag:1bHh0w5ev7nNt8qS8qmvFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
