---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi