# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    SECRET_INT_DOMAIN: home.limb.network
    SECRET_INT_CERT_DOMAIN: home-limb-network
    SECRET_AWS_BUCKET: home-lab-velero-backup
    SECRET_KS_DOMAIN: k8s.int.v4d3r.xyz
    SECRET_KS_CERT_DOMAIN: k8s-int-v4d3r-xyz
    SECRET_MAIL_ADDR: john.limb@limb.network
    SECRET_PGADMIN_PASS: e944dal
    SECRET_IMMICH_DB_PASS: B56xQVqeJreRCmnY
    JWT_SECERET: DeD9q9F3GNac04857ulU
    SECRET_SLACK_URL_REBOOT: slack://hook:T04GJJ67VM5-B04KS6EMV1U-uimJZLRQxvr9XTX92HJJqiQ3@webhook?color=good&title=kured-notification&icon=man-scientist&botname=kured
