apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: networking-system
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.${SECRET_INT_DOMAIN}`)
      kind: Rule
      middlewares:
        - name: traefik-dashboard-basicauth
          namespace: networking-system
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    secretName: prod-traefik-${SECRET_INT_CERT_DOMAIN}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.${SECRET_INT_DOMAIN}
  namespace: networking-system
spec:
  secretName: prod-traefik-${SECRET_INT_CERT_DOMAIN}
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "traefik.${SECRET_INT_DOMAIN}"
  dnsNames:
  - "traefik.${SECRET_INT_DOMAIN}"