apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-traefik
  namespace: flux-system
spec:
  path: ./clusters/prod/Apps/Networking/traefik/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  dependsOn: 
    - networking-system-metallb
  prune: false
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: networking-system
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: networking-system-traefik
  interval: 5m
  path: "./clusters/prod/Apps/Networking/traefik/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system