apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-cert-manager
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/cert-manager/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  dependsOn:
  - name: networking-system-metallb
  prune: false
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-cert-manager
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
  - name: app-cert-manager
  interval: 30m
  path: "./clusters/prod/Apps/cert-manager/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
