apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-unifi
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Networking/Unifi/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  dependsOn: 
    - name: networking-system-metallb
  prune: false
  wait: true
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-ingress-unifi-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: networking-system-unifi
  interval: 30m
  path: "./clusters/prod/Apps/Networking/Unifi/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system