---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: ${TZ}
    hajimari:
      title: hajimari-${SECRET_INT_CERT_DOMAIN}
      darkTheme: lime
      customThemes:
       - name: Temp
         backgroundColor: '#3a1c46'
         primaryColor: '#ffffff'
         accentColor: '#FF235A'
      alwaysTargetBlank: true
      showGreeting: true
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - monitoring
          - networking-system
          - longhorn-system
      name: "V4d3r"
      customApps:
        - group: O365
          apps:
            - name: Outlook
              url: 'https://outlook.com'
              icon: 'mdi:microsoft-outlook'
              info: outlook
            - name: OneDrive
              url: 'https://onedrive.live.com'
              icon: 'mdi:microsoft-onedrive'
              info: ondedrive
      globalBookmarks:
      - group: Communicate
        bookmarks:
          - name: Discord
            url: 'https://discord.com'
          - name: Gmail
            url: 'http://gmail.com'
            icon: 'mdi:gmail'
          - name: Slack
            url: 'https://slack.com/signin'
            icon: 'mdi:slack'
          - name: GoogleDrive
            url: 'https://drive.google.com'
            icon: 'mdi:google-drive'
      - group: Dev
        bookmarks:
          - name: AdGuard
            url: 'https://adguard-dns.io/'
            icon: 'mdi:server-security'
          - name: Github
            url: 'https://github.com'
            icon: 'mdi:github'
    persistence:
      data:
        enabled: true
        type: emptyDir
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
