---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      TZ: ${TZ}
    hajimari:
      title: hajimari-${SECRET_INT_CERT_DOMAIN}
      darkTheme: lime
      alwaysTargetBlank: true
      showGreeting: true
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: true
      showGlobalBookmarks: true
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - monitoring
          - networking-system
          - longhorn-system
      name: "home"
      customApps:
        - name: NAS
          url: http://192.168.1.100
          icon: nas
      groups:
        - name: Online
          links:
           - name: Discord
             url: 'https://discord.com' 
    persistence:
      data:
        enabled: true
        type: emptyDir
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128M
