apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-kube-prometheus
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Monitoring/kube-prometheus-stack/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: true
  wait: true
  dependsOn:
  - name: longhorn-system-longhorn
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-kube-prometheus-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
  - name: monitoring-kube-prometheus
  interval: 30m
  path: "./clusters/prod/Apps/Monitoring/kube-prometheus-stack/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
