apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:tl9dQCyK4+6z36nWADOEsO4GHA9qP9CWCHL4CGbgcwPtw+YLxcEpLg==,iv:HBvm91GMJqZsn1hbGf9xwvRRVk3EbvwNw33JtKkvc5c=,tag:KrPYHXM/2WXQwkFyjdDisw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUUl3MVRSNExDV1Rpd3hu
            QkpBL3pwYUV2bXdFakZoR25zWmRLYnRLUnpvCk1VQ0FORkloZStxWGhlRzJVR0VK
            d2svSjlXWTJ0NkNNblpWZHd5aHZiYlkKLS0tIHlUSlJqVkI2SS81V3J3Z2wwbmNX
            RTVBTGxnRkNrVFFLalIwRlFRV2w5NkkKG1oR0J9d35UWsMT2RVTnA5GHsK9hy8Py
            Tq43fidhVa+TwY0d6pagC1SSMFvNMo0ouAFSvHhciNf8roFHvJoYOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T11:05:44Z"
    mac: ENC[AES256_GCM,data:QVXfdvYN/lDk+vW40tDW0ZOHDVXneo5cH+usnVoanVxCAq3qmSHlMNwRJQXsSnUgMYTH7WFZfFC/Pur95p2SgyKztDT3nf1BIkctC9ls+e207i098cSsHl8tllBZKbYymuNNlBbyH9eYE0dnq8hlc4eJsnvIY46h02AZbziyNAI=,iv:hqT0rPFgmoKnHSJCcREQ5Li05y1h8G4GfoFcK0nBeYQ=,tag:MVc27aWg7VCkHxFRHRF1bg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
