---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale-relay
  namespace: networking-system
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-relay
      version: 0.1.12
      sourceRef:
        kind: HelmRepository
        name: mvisonneau
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: docker.io/mvisonneau/tailscale
      tag: 'v1.34.1'
    config:
      variables:
        TAILSCALE_ADVERTISE_ROUTES: "192.168.1.0/24,192.168.2.0/24"
  valuesFrom:
    - kind: Secret
      name: tailscale-secret
      valuesKey: tailscale-token
      targetPath: config.authKey
