---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: hajimari.${SECRET_INT_DOMAIN}
      namespace: default
    spec:
      secretName: prod-hajimari-${SECRET_INT_CERT_DOMAIN}
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      commonName: "hajimari.${SECRET_INT_DOMAIN}"
      dnsNames:
      - "hajimari.${SECRET_INT_DOMAIN}"