apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joplin
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 6
  upgrade:
    remediation:
      retries: 6
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    image:
      repository: joplin/server
      tag: 2.12.1-beta
      pullPolicy: IfNotPresent
    service:
      main:
        ports:
          http:
            port: 22300
    env:
      TZ: "${TZ}"
      APP_BASE_URL: "https://joplin.${SECRET_INT_DOMAIN}"
      APP_PORT: 22300
      DB_CLIENT: pg
      POSTGRES_HOST: app-cluster-rw.database.svc.cluster.local
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: joplin
      MAILER_ENABLED: 0
      POSTGRES_PASSWORD: ${SECRET_JOPLIN_DB_PASS}
      POSTGRES_USER: joplin

