---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress-nginx
  namespace: longhorn-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: longhorn.${SECRET_INT_DOMAIN}
spec:
  ingressClassName: nginx
  tls:
   - hosts:
     - longhorn.${SECRET_INT_DOMAIN}
     secretName: prod-longhorn-${SECRET_INT_CERT_DOMAIN}
  rules:
    - host: "longhorn.${SECRET_INT_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
---
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: longhorn.${SECRET_INT_DOMAIN}
      namespace: longhorn-system
    spec:
      secretName: prod-longhorn-${SECRET_INT_CERT_DOMAIN}
      issuerRef:
        name: letsencrypt-production
        kind: ClusterIssuer
      commonName: "longhorn.${SECRET_INT_DOMAIN}"
      dnsNames:
      - "longhorn.${SECRET_INT_DOMAIN}"