apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-system-longhorn
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Storage/Longhorn/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: false
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: longhorn-system-longhorn-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: longhorn-system-longhorn
  interval: 5m
  path: "./clusters/prod/Apps/Storage/Longhorn/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system