---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  IMMICH_WEB_URL: http://immich-web.media.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
  TYPESENSE_HOST: immich-typesense.media.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config