---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-configmap
  namespace: media
data:
  DB_PORT: "5432"
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: app-cluster-rw.database.svc.cluster.local
  DB_USERNAME: immich
  DB_PASSWORD: ${SECRET_IMMICH_DB_PASS}
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: redis-headless.database.svc.cluster.local
  REDIS_PORT: "26379"
  REDIS_DBINDEX: "0"
  IMMICH_WEB_URL: http://immich-web.media.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.media.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003