---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: code-server
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: wrmilling
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: codercom/code-server
      tag: 4.11.0
    persistence:
      enabled: true
      existingClaim: code-server-pvc
    extraVars:
      - name: DISABLE_TELEMETRY
        value: "true"