---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    image:
      repository: dpage/pgadmin4
      tag: "7.1"
    strategy:
      type: RollingUpdate
    env:
      email: ${SECRET_MAIL_ADDR}
      password: ${SECRET_PGADMIN_PASS}
    persistentVolume:
      enabled: true
      existingClaim: pgadmin
    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 236M
    serverDefinitions:
            enabled: true
            servers:
                app-cluster:
                    Name: app-cluster
                    Group: Servers
                    Port: 5432
                    Username: app
                    Host: app-cluster-rw.database.svc.cluster.local
                    SSLMode: prefer
                    MaintenanceDB: app
