---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    image:
      repository: dpage/pgadmin4
      tag: "6.19"
    strategy:
      type: Recreate
    env:
      email: ${SECRET_MAIL_ADDR}
      password: ${SECRET_PGADMIN_PASS}
    persistentVolume:
      enabled: true
      existingClaim: pgadmin
    resources:
      requests:
        cpu: 15m
        memory: 164M
      limits:
        memory: 236M
    serverDefinitions:
            enabled: true
            servers:
                core:
                    Name: postgres
                    Group: Servers
                    Port: 5432
                    Username: postgres
                    Host: postgres.database.svc.cluster.local
                    SSLMode: prefer
                    MaintenanceDB: postgres
