---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin
  namespace: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi