---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: libreddit
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: ghcr.io/auricom/libreddit
      tag: 0.29.4
    env:
      LIBREDDIT_DEFAULT_SHOW_NSFW: true
    service:
      main:
        ports:
          http:
            port: 8080
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
      limits:
        memory: 250Mi
