---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-cluster
  namespace: database
spec:
 instances: 2
 imageName: ghcr.io/cloudnative-pg/postgresql:14.6
 primaryUpdateStrategy: unsupervised
 storage:
   size: 20Gi
   storageClass: longhorn
 postgresql:
   parameters:
     max_connections: "300"
     shared_buffers: 512MB
 superuserSecret:
   name: postgres-superuser-secret
 monitoring:
   disableDefaultQueries: false
   enablePodMonitor: true