apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-app-db
spec:
  instances: 1
  superuserSecret:
    name: postgres-superuser-secret
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret
  storage:
    size: 1Gi
