---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-cluster
  namespace: database
spec:
 instances: 2
 imageName: ghcr.io/cloudnative-pg/postgresql:14.6
 primaryUpdateStrategy: unsupervised
 storage:
   size: 20Gi
   storageClass: longhorn
 postgresql:
   parameters:
     max_connections: "300"
     shared_buffers: 512MB
 superuserSecret:
   name: postgres-superuser-secret
 bootstrap:
    initdb:
       database: app
       owner: app
       secret:
        name: appdb-user-secret
       postInitSQL:
         - CREATE DATABASE IF NOT EXISTS immich
         - CREATE USER IF NOT EXISTS immich with encrypted password '${SECRET_IMMICH_DB_PASS}'
         - GRANT ALL privileges on database immich to immich
 monitoring:
   disableDefaultQueries: false
   enablePodMonitor: true