---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: app-cluster
  namespace: database
spec:
 instances: 2
 imageName: ghcr.io/cloudnative-pg/postgresql:14.6
 primaryUpdateStrategy: unsupervised
 storage:
   size: 20Gi
   storageClass: longhorn
 postgresql:
   parameters:
     max_connections: "300"
     shared_buffers: 512MB
 superuserSecret:
   name: postgres-superuser-secret
 bootstrap:
    initdb:
       database: app
       owner: app
       secret:
        name: appdb-user-secret
 monitoring:
   disableDefaultQueries: false
   enablePodMonitor: true
 backup:
   retentionPolicy: "10d"
   barmanObjectStore:
     destinationPath: "S3://${SECRET_AWS_POSTGRES_BUCKET}"
     s3Credentials:
       accessKeyId:
         name: aws-creds-backup
         key: AWS_ACCESS_KEY_ID
       secretAccessKey:
         name: aws-creds-backup
         key: AWS_SECRET_ACCESS_KEY