---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: networking-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    controller:
      extraEnvs:
        - name: TZ
          value: "${TZ}"
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: |-
            ${METALLB_INGRESS_ADDR}
        externalTrafficPolicy: Local
  