apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-metallb
  namespace: flux-system
spec:
  path: ./clusters/prod/Apps/Networking/metallb/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: false
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: networking-system-metallb
  interval: 30m
  path: "./clusters/prod/Apps/Networking/metallb/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system