apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-pgadmin
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Database/pgadmin/App
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: false
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: pgadmin
      namespace: database
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-pgadmin-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: apps-pgadmin
  interval: 5m
  path: "./clusters/prod/Apps/Datbase/pgadmin/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system