apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-external-dns
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Networking/external-dns/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
