apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-external-dns
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Networking/external-dns/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  prune: false
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-dns
      namespace: networking-system
  timeout: 5m
