---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        name: bjw-s-charts
        kind: HelmRepository
        namespace: flux-system
      version: 1.2.1
  interval: 30m
  maxHistory: 2
  install:
    createNamespace: True
    remediation: 
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 2
  uninstall:
    keepHistory: false
  dependsOn:
   - name: immich-proxy
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.43.1
    command: /bin/sh
    args:
      - ./entrypoint.sh
    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        mountPath: /usr/src/app/upload
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 2000Mi