apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-ingress-nginx
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./clusters/prod/Apps/Networking/ingress-nginx/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m
  dependsOn:
  - name: networking-system-metallb
  prune: true
  wait: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-system-ingress-nginx-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
  - name: app-cert-manager
  interval: 10m
  timeout: 5m
  path: "./clusters/prod/Apps/Networking/ingress-nginx/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
