---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-data
  namespace: networking-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
