apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cyberchef
  namespace: development
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
    image:
      repository: docker.io/mpepping/cyberchef
      tag: v10.4.0
    env:
      TZ: ${TZ}
    service:
      main:
        ports:
          http:
            port: 8000
