apiVersion: v1
stringData:
    admin-password: ENC[AES256_GCM,data:MYQO2ryHSaGGKX8z,iv:Xf713lBtuNGY8Lma3fl5V+UDdOeEIlHkQbNqKl2CxTw=,tag:OsejwTg9nBDEXI17/R8oaQ==,type:str]
    admin-user: ENC[AES256_GCM,data:fVO8ag==,iv:V9bH2ks++HxTQNvx/4CWiFbQz1m3YGvVStqZUsu+kRM=,tag:HLxzsoSUSLGe5vhgyk3mlA==,type:str]
kind: Secret
metadata:
    name: appdb-secret
    namespace: database
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Qm1jS3p0MkVQUSt5ZnZC
            SEZyRWZjd1p1S2lYY3diNHVzRjVKVk45QXlVCjMzZk4rVzJDQ2hSVjNzNHdKZjJJ
            eXg0aXZ1Y3BCSXNmQzhkdCs2TEl5b0kKLS0tIEc4dlpHVm1hMXkwWkRDcjVyMEgy
            YmIzd1hTeEl5WTFtS1VCSVUzaG9Jd0UKUHbkcIs3iV3vESzGrNEaZm8P603tgX+s
            9ZjZgQw3BhhA6bcb4+6gb4/H8vNmWj7m/7EbatgNkZgGTGTH9d1FJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T15:47:17Z"
    mac: ENC[AES256_GCM,data:om+FYEg23H2xg6SKnb+pZ8TBGJOr7DyM8+fCgnVoUgQ6c0QX6OtKWdXXgijKU54Uj58cDSO8DNhVpSa+MDra62OSnmUKfbNQk+8w0OTmVfjKea+BodPNLXrd9LZvLiS2lJ2GCyYe59yxppgGNldO669JzeNySQHihxMmuV9uCBM=,iv:hQip1LVCbxNANeYYLcxikbGrW5NBZLLwBbbgZgF0fho=,tag:jSpJfrrckziA46NDit6/uA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
