apiVersion: v1
data:
    username: ENC[AES256_GCM,data:W72yJLy0,iv:BKaws/pwAmH+9h3TE7nNKgUaf4EHqYw0jWjK+Huf2l0=,tag:vTZ1HhS4lbieVW5m60m4qg==,type:str]
    password: ENC[AES256_GCM,data:TVSFW4HJtyWdWRnB5jAUVcWBLj0yiKLC,iv:POdpbXjPS4QSTF5e/gkOs5iijKUJOdFpaWOw77fxRjU=,tag:MxKS15TxYAgMs+9K4o/qdQ==,type:str]
kind: Secret
metadata:
    name: appdb-user-secret
    namespace: database
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTGwxN1U0K0UxSWRwNU11
            TjhWRER5Yk05ZWZ6M3g4UG5hU0crMkFSUGlrCjZsaFo3WU8xQnVCMHFJWGJvSWd5
            anBaSVlZdU9VbmJ5U1c3UzdzMTlkTEkKLS0tIEo4OW5hOXUwYVlMT1ZlaFlCUlBm
            UEMrS0VZcUlGQXlsYklpRGRzaStucEUKyfxP/9o0YZZRxC7KevrNE98z13NYqCwS
            /C/1Ol32OlgpfQYk2NO1ZObbww5+RFae9qatby9Ejgwkl6MuCMU+sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T21:45:42Z"
    mac: ENC[AES256_GCM,data:a7qodTHU4B/o/WlUN5pzScddewWvSt/2fAfIECXvoKfAQjVnoxUZnyIfeWlXTWvy+EXLBDrrcEUXW+f5De/MK12vJDFe3POyiKelpX8cKpODtt70IbhBeEKxt8WvAPaeLdH2b/oyck2CuIQRBknmkxrQKc3Gi4VMO8e6xuYrZpM=,iv:ftat1gJ/Q2jFNQRv2qpGf7P9yqlxtZo3TOwghJ0gc8g=,tag:SV+leIJU3KHJnaYLWESpYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
