kind: Secret
metadata:
    name: postgres-superuser-secret
    namespace: database
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    password: ENC[AES256_GCM,data:BEMtdAc00iE=,iv:1fWFm/GgPVfwbcAPTDcxQ1D5hOL/JDhB9krv2JbEGEE=,tag:3kPG1s6XXOh/zEcwKY8vtw==,type:str]
    username: ENC[AES256_GCM,data:cX0Qjg44RB0=,iv:pd+pYq1a2A/FewRUiC+LD4vdz7cpRy/6savh5S2H6dA=,tag:ihdIjCEJSfnP7RRs4dIx8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeGtOKzJaVkRETmR5NGFU
            MitRQzhITEpYbU5keWNXOHlzU2FrZXNCaGo4CktxUjBpUWtPZXpDOTYxMmhqa2w0
            UjRQK0Z0WmUvUitPb2lweWN2M1R2OVEKLS0tIGRPT0dKSUVIK0V5NXYyZGRLcTB0
            czdpNjU3Mm5KdEVDMlE2SmQwSGJPL1kKehoPrjKq8YEHZ/oTRcqQWAPwQZ9LXDVv
            isnihygV4K/uzHuC+PpsuIzSHAd/S2SQvUo4/3wgglZqRr5nzClhLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-25T18:55:54Z"
    mac: ENC[AES256_GCM,data:Y7SFRCf7+QTT5gLdCazbX4EM5ti3n0D8gze6fWOPxLT73k0DKNpISzt3wjOchIZ8uhJoOnxKuDwA5HJsMdjGMBFK3vxzZmMKy4XVV+AhnIQ5DWrdEbyypzKzow6SUvNyPqqFoG5BVSS/ftYik5iBKVjES7IJjt//iTaNHosF8vU=,iv:18OupIaegolZlKXjq+O4oHiM0ji+qCctvMv2NiXO7Bo=,tag:Bat02hF1vbQ7urECz4c0Aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
