apiVersion: v1
kind: Secret
metadata:
    name: aws-creds-backup
    namespace: database
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ddPiv2fy0DMG0uPHZ1ltk3P3X7/VNKdziJhdHw==,iv:A/3VMj2V2q/grNTVZXmBNVA4XOo462MiwYUxooqTIMk=,tag:6m46uHESeBM/vRgim2bzZg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CcaykvwqJJzmFlsIKTPH75dUHzgnrc4r2BWPmE1Mm8acJPzvmewzjfRBI7NkJCoIZZ8vNjl0OjQ=,iv:MejCsBiZK3RZGofMLNHPc15XmpmT3dLq01ZP9/012aQ=,tag:6qtjA+JTQqKchTkHFog+nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1a0q20utj6v2s7tajn7l8kwua0ga0aqple75mpvqfjt40t3za7fsqecmmxc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z3FYaXUrTTZXcFRiN2VZ
            aDc2bU1KOVdmelpiYjlRU1pkSzBZTDhyeTJrCnZEYkpxT3VZWFY0ek9jdTN6RTZy
            ci9scjNSRHMxL2VTekN0NHVRYWVma28KLS0tIHZPSFJmOUwvc1UxT2FxcWptUlVY
            QXBkMUdkWElXeFZERzN0dU5ydUduSnMKvRSgQXtoztHTk8unD2b2KAWibwnvjnmH
            uxPuhEKg8ICBmSxo8zbBMPPACasO04mf+Rb01icrcUBIKQQ+WaCkBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T20:16:25Z"
    mac: ENC[AES256_GCM,data:ej8hVWd4qbRk82ArPkkgIosn5q2+FkmGEUcBUsjjbWbPLOtptVKWk+lbZ+CzywGWaVMaphZITY1wtnFhzPOS/1wqhx1dwJUzTK8oEbcLKGrXy0z5OhKnDHEaeDgT+jTg9zeLPafJqBE7+ZMEctYz/JF8+CF0vrhPYnqX0WIzyoo=,iv:sf4u+XipW7+b4cjsxDkOsYd+OO7ZvXxnt0+tLyGI3+0=,tag:HwLUvC+i9m1+O6AC7ZITtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
